FROM node:22-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY dist ./dist
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "start", "--", "--ip", "0.0.0.0", "--port", "3000"]
